<?php
/***** PDP GALLERY */
$_galleryImages = $block->getGalleryImages(); // Get the gallery images
$_product = $block->getProduct(); // Get the product
?>

<?php if ($_galleryImages && count($_galleryImages) > 0): ?>
    <div class="product-gallery-grid">
        <div class="product-gallery">
            <?php foreach ($_galleryImages as $_image): ?>
                <div class="product-gallery_slide">
                    <div class="gallery-item">
                        <a href="<?= $block->escapeUrl($_image->getUrl()) ?>" class="gallery-item-link" title="<?= $_product->getName() ?>">
                            <img src="<?= $block->escapeUrl($_image->getUrl()) ?>" alt="<?= $_product->getName() ?>" class="img-responsive"/>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

